/**
 * Enriched Data Panel Component
 * 
 * Displays enriched context text generated by the Data Enrichment Layer.
 * Includes collapsible sections, copy functionality, and character/token count.
 * 
 * @component
 */

import React, { useState } from 'react';
import styles from './EnrichedDataPanel.module.css';

/**
 * @typedef {Object} EnrichedDataPanelProps
 * @property {string} enrichedContext - Enriched context text
 * @property {boolean} isEnrichmentEnabled - Whether enrichment is enabled
 */

/**
 * EnrichedDataPanel component for displaying enriched assessment context
 * @param {EnrichedDataPanelProps} props
 */
export default function EnrichedDataPanel({ 
  enrichedContext = '', 
  isEnrichmentEnabled = true 
}) {
  const [expandedSections, setExpandedSections] = useState({
    scoreInterpretations: true,
    domainMappings: true,
    traitInsights: true,
    roleRationale: true,
    centralTension: true
  });
  const [copySuccess, setCopySuccess] = useState(false);

  // Parse enriched context into sections
  const parseSections = (text) => {
    if (!text) return {};

    const sections = {};
    const sectionHeaders = [
      'SCORE INTERPRETATIONS',
      'DOMAIN MAPPINGS',
      'TRAIT INSIGHTS',
      'ROLE MATCH RATIONALE',
      'CENTRAL TENSION'
    ];

    let currentSection = null;
    let currentContent = [];

    const lines = text.split('\n');
    
    for (const line of lines) {
      const trimmedLine = line.trim();
      // Remove trailing colon for comparison
      const lineWithoutColon = trimmedLine.replace(/:$/, '');
      
      // Check if line is a section header (with or without colon)
      if (sectionHeaders.includes(lineWithoutColon)) {
        // Save previous section
        if (currentSection) {
          sections[currentSection] = currentContent.join('\n').trim();
        }
        
        // Start new section (use header without colon as key)
        currentSection = lineWithoutColon;
        currentContent = [];
      } else if (currentSection) {
        currentContent.push(line);
      }
    }

    // Save last section
    if (currentSection) {
      sections[currentSection] = currentContent.join('\n').trim();
    }

    return sections;
  };

  const sections = parseSections(enrichedContext);

  // Toggle section expansion
  const toggleSection = (sectionKey) => {
    setExpandedSections(prev => ({
      ...prev,
      [sectionKey]: !prev[sectionKey]
    }));
  };

  // Copy to clipboard
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(enrichedContext);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (error) {
      console.error('Failed to copy:', error);
      alert('Failed to copy to clipboard');
    }
  };

  // Expand/collapse all sections
  const handleExpandAll = () => {
    const allExpanded = Object.values(expandedSections).every(v => v);
    const newState = {};
    Object.keys(expandedSections).forEach(key => {
      newState[key] = !allExpanded;
    });
    setExpandedSections(newState);
  };

  // Calculate stats
  const charCount = enrichedContext.length;
  const lineCount = enrichedContext.split('\n').length;
  // Rough token estimate (1 token ≈ 4 characters)
  const tokenEstimate = Math.ceil(charCount / 4);

  // Section key mapping
  const sectionKeyMap = {
    'SCORE INTERPRETATIONS': 'scoreInterpretations',
    'DOMAIN MAPPINGS': 'domainMappings',
    'TRAIT INSIGHTS': 'traitInsights',
    'ROLE MATCH RATIONALE': 'roleRationale',
    'CENTRAL TENSION': 'centralTension'
  };

  if (!isEnrichmentEnabled) {
    return (
      <div className={styles.enrichedDataPanel} style={{ color: '#000', backgroundColor: '#fff' }}>
        <div className={styles.header}>
          <h2 className={styles.title} style={{ color: '#000' }}>Enriched Context</h2>
        </div>
        <div className={styles.disabledMessage} style={{ color: '#000' }}>
          <p style={{ color: '#000' }}>Data enrichment is currently disabled.</p>
          <p style={{ color: '#000' }}>Enable enrichment in the Control Panel to see enriched context.</p>
        </div>
      </div>
    );
  }

  if (!enrichedContext) {
    return (
      <div className={styles.enrichedDataPanel} style={{ color: '#000', backgroundColor: '#fff' }}>
        <div className={styles.header}>
          <h2 className={styles.title} style={{ color: '#000' }}>Enriched Context</h2>
        </div>
        <div className={styles.emptyMessage} style={{ color: '#000' }}>
          <p style={{ color: '#000' }}>No enriched context available.</p>
          <p style={{ color: '#000' }}>Generate a report to see enriched assessment data.</p>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.enrichedDataPanel} style={{ color: '#000', backgroundColor: '#fff' }}>
      <div className={styles.header}>
        <h2 className={styles.title} style={{ color: '#000' }}>Enriched Context</h2>
      </div>

      {/* Toolbar */}
      <div className={styles.toolbar}>
        <button onClick={handleExpandAll} className={styles.toolbarButton} style={{ color: '#000' }}>
          {Object.values(expandedSections).every(v => v) ? '▼ Collapse All' : '▶ Expand All'}
        </button>
        
        <button onClick={handleCopy} className={styles.toolbarButton} style={{ color: '#000' }}>
          {copySuccess ? '✓ Copied!' : '📋 Copy'}
        </button>

        <div className={styles.stats}>
          <span className={styles.stat} style={{ color: '#000' }}>{lineCount} lines</span>
          <span className={styles.stat} style={{ color: '#000' }}>{charCount.toLocaleString()} chars</span>
          <span className={styles.stat} style={{ color: '#000' }}>~{tokenEstimate.toLocaleString()} tokens</span>
        </div>
      </div>

      {/* Sections */}
      <div className={styles.sectionsContainer} style={{ color: '#000' }}>
        {Object.entries(sections).map(([header, content]) => {
          const sectionKey = sectionKeyMap[header];
          const isExpanded = expandedSections[sectionKey];

          return (
            <div key={header} className={styles.section} style={{ backgroundColor: '#fff' }}>
              <button
                onClick={() => toggleSection(sectionKey)}
                className={styles.sectionHeader}
                style={{ color: '#000' }}
              >
                <span className={styles.sectionIcon} style={{ color: '#000' }}>
                  {isExpanded ? '▼' : '▶'}
                </span>
                <span className={styles.sectionTitle} style={{ color: '#000' }}>{header}</span>
              </button>
              
              {isExpanded && (
                <div className={styles.sectionContent} style={{ color: '#000', backgroundColor: '#fafafa' }}>
                  <pre className={styles.contentText} style={{ color: '#000', backgroundColor: '#fafafa' }}>{content}</pre>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
